# Generated by Django 2.0.5 on 2018-05-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedItam',
            new_name='ProfileFeedItem',
        ),
    ]
